[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "rl_project"
version = "0.0.1"
authors = [
  { name="anantoj", email="gg.ananto@gmail.com" },
]
requires-python = ">=3.6"
